### ISSUE TITLE
should the while loop variable be mut?

### ISSUE THREAD

**Issue by fbstj** [steveklabnik/rust-in-ten-slides#1]
https://github.com/steveklabnik/rust-in-ten-slides/blob/399e3d63a2268194aec4b1fc6db39fe3ecfa6844/basic-syntax.html#L202

should it be
```rust
let mut done = false;
```

as it gets changed in the loop:

https://github.com/steveklabnik/rust-in-ten-slides/blob/399e3d63a2268194aec4b1fc6db39fe3ecfa6844/basic-syntax.html#L207

**Comment by steveklabnik** [comment]
Yup, nice catch! Do you want to send in a PR or should I just fix it?

**Comment by steveklabnik** [comment]
fixed by https://github.com/steveklabnik/rust-in-ten-slides/pull/3
